# syntax=docker/dockerfile:1
FROM python:3.10
WORKDIR /code
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
COPY requirements.txt .
RUN pip install --upgrade -r requirements.txt
EXPOSE 5000
CMD ["uwsgi", "--ini", "config/uwsgi.ini"]
