version: "3.9"
services:
  redis:
    image: redis:6-alpine
  flask:
    build: .
    depends_on:
      - redis
    expose:
      - 5000
    command: uwsgi --ini instance.ini
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "443:443"
    depends_on:
      - flask
