version: "3.9"
services:
  redis:
    image: redis:6-alpine
    volumes:
      - "./data:/data"
    profiles:
      - dev
      - prod
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    depends_on:
      - redis
    expose:
      - 5000
    profiles:
      - prod
    volumes:
      - "./:/code"
  flask-dev:
    build:
      context: .
      dockerfile: Dockerfile-flask
    depends_on:
      - redis
    ports:
      - "5000:5000"
    profiles:
      - dev
    volumes:
      - "./:/code"
    command: ["flask", "run"]
    environment:
      FLASK_ENVIRONMENT: development
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "443:443"
    depends_on:
      - flask
    profiles:
      - prod
