default:
  burgundy: "#6D001A"
  dark red: "#BE0039"
  red: "#FF4500"
  orange: "#FFA800"
  yellow: "#FFD635"
  pale yellow: "#FFF8B8"
  dark green: "#00A368"
  green: "#00CC78"
  light green: "#7EED56"
  dark teal: "#00756F"
  teal: "#009EAA"
  light teal: "#00CCC0"
  dark blue: "#2450A4"
  blue: "#3690EA"
  light blue: "#51E9F4"
  indigo: "#493AC1"
  periwinkle: "#6A5CFF"
  lavender: "#94B3FF"
  dark purple: "#811E9F"
  purple: "#B44AC0"
  pale purple: "#E4ABFF"
  magenta: "#DE107F"
  pink: "#FF3881"
  light pink: "#FF99AA"
  dark brown: "#6D482F"
  brown: "#9C6926"
  beige: "#FFB470"
  black: "#000000"
  dark gray: "#515252"
  gray: "#898D90"
  light gray: "#D4D7D9"
  white: "#FFFFFF"
